### ISSUE TITLE
Remove dependence on operator-sdk

### ISSUE THREAD

**Issue by fahlmant** [openshift/operator-custom-metrics#28]
Operator-sdk is only used to get the operator name and namespace to name the service and create the resource. The name could be passed in via the configuration, and namespace can be infered from the pod with an optional override configuration.

**Comment by 2uasimojo** [comment]
I'm curious how you plan to infer the namespace from the pod. I made quite a mess when I tried:

https://github.com/openshift/aws-efs-operator/blob/c6665d043a2cb2dad42382facd8942655f2418a2/pkg/controller/statics/statics.go#L152-L185

You'll notice I accounted for three variations:
- Running in cluster
- Running "locally" (`operator-sdk run --local`)
- Running unit tests.

**Comment by 2uasimojo** [comment]
It should be legit to infer the operator name from the name of the repository. They should be the same for all of the operators "we" (SRE-P?) own, and if it's not, we're going to try to make it so when we standardize. If so, you can seed the configuration from something like [this](https://gitlab.cee.redhat.com/service/boilerplate/-/blob/efd44b6c521ce25a5d887ef89f8c7bfb1b0cd94c/boilerplate/update#L54). In fact, once this operator has assimilated the above boilerplate, seeding that configuration will actually be part of the convention.

**Comment by fahlmant** [comment]
@2uasimojo This library is used in SREP operators but in theory could be used for any operator, so I'm trying to keep the configuration non-specific to our workload (and really this code other than the operator-sdk dependency can be run on any kubernetes workload, not just operators).

I just assumed inferring namespace when accessing the kube api from within that namespace would be easy, but if that's too diffucult, adding namespace as part of the builder config should be simple:

.WithNamespace("mynamespace")

**Comment by 2uasimojo** [comment]
> I just assumed inferring namespace when accessing the kube api from within that namespace would be easy, but if that's too diffucult, adding namespace as part of the builder config should be simple:
> 
> .WithNamespace("mynamespace")

I think this make sense -- leave it up to the consumer to do namespace discovery however they see fit. As hinted above, discovering the namespace when running in a cluster isn't especially hard; what's tough is also accommodating testing setups.

Come to think of it, a method such as [this](https://github.com/openshift/aws-efs-operator/blob/c6665d043a2cb2dad42382facd8942655f2418a2/pkg/controller/statics/statics.go#L152-L185) to do namespace discovery that accounts for the three possible ways you could be running your operator code (in-cluster, local, unit test) wouldn't be a terrible thing to propose to operator-sdk itself. /me cards... [OSD-4353](https://issues.redhat.com/browse/OSD-4353)

**Comment by fahlmant** [comment]
Done with the release of v0.4.0
