### ISSUE TITLE
Support ServiceMonitor

### ISSUE THREAD

**Issue by fahlmant** [openshift/operator-custom-metrics#6]
Currently, the only way to access the Service created is through a Route. If the user wants to expose metrics to a local prometheus, the standard way is via a ServiceMonitor. 

Thinking about the API and the builder pattern, perhaps we could simple add a `WithServiceMonitor()` function, and create a `WithRoute()` as well so the way to expose the Service is explicit. Not sure what the default should be. Maybe nothing, since the Service will always be there.

@varshaprasad96 @rafael-azevedo @rogbas Thoughts?

**Comment by varshaprasad96** [comment]
I agree, we could create a WithServiceMonitor() function to provide support to expose metrics to a local Prometheus.  Or we can either create a Service Monitor resource by default, along with the service. It can be up to the user to include the service monitor in their prometheus instance or just ignore it.

But creation of route need not be optional. In case of a standalone Prometheus deployment (not through Prometheus operator), the endpoint for the metrics can be directly provided in the configuration file to scrape the metrics. And if a Prometheus operator is used, the endpoint can be used to just check / view the metrics. So, I suppose WithRoute() function is not required. We can by default create a route when a set of metrics is getting exposed.

**Comment by fahlmant** [comment]
What if a user does not want to expose their metrics outside of the cluster? Or wants to use a non-Openshift specific way of exposing their metrics?

**Comment by varshaprasad96** [comment]
True!. That may be a valid case. But if the library is supporting non-openshift users, then do we focus on kubernetes nodeport or load-balancer IP creation? Wouldn't that be complicated, because we don't know the cluster properties.

**Comment by fahlmant** [comment]
The implementation of those things will be difficult but also far in the future. I'm mostly trying to get the API in a place that is easy to allow for those configs to be added in the future. Or even if a user just wants to deploy those objects themselves. The only things needed to guarantee that metrics work is the port, path and service. Over the service could be many different objects to expose the data.

**Comment by fahlmant** [comment]
Completed in #8
